### ISSUE TITLE
Add more SearchProperties to the Use and By classes like AccessibleName, HelpText, ControlName, FriendlyName, DisplayText

### ISSUE THREAD

**Issue by TsvetomirSlavovPortfolio** [DavidWDev/DW.CodedUI#3]

**Comment by DavidWDev** [comment]
Thank you, I will have a look :-)
Till I made new properties you can use
By.Condition(a => a.Property == expected).

**Comment by TsvetomirSlavovPortfolio** [comment]
David, could you add also Id, ControlId, and AccessibleDescription.

**Comment by DavidWDev** [comment]
Hi,

AccessibleName = Not available by the AutomationElement
HelpText = Possible
ControlName = Is already there with the property "Name"
FriendlyName = Not available by the AutomationElement
DisplayText = Depending on the control type, its already there. Either Name or Text. See BasicEdit, BasicText, BasicElement
InnerText = See DisplayText. A more concrete InnerText I cannot provide to the By Condition because its not valid for all AutomationElements.
Class = Possible by providing directly "ControlType"
ClassName = Possible
Id = Automation ID? Its already there
ControlId = Not available by the AutomationElement
AccessibleDescription = Not available by the AutomationElement

Since only HelpText, ClassName and maybe Class only would be possible, I decided to not to change anything.

Consider using By.Condition(element => elemement.Property == expected) or similar.
