### ISSUE TITLE
TreeViewItem.Unsafe.Expand() throws NotSupportedException

### ISSUE THREAD

**Issue by Georgie89** [DavidWDev/DW.CodedUI#4]
Hello, 
I was just trying to use your framework for creating a test suite for our application and found the following issue:
-I was defined a property with the type of BasicTreeViewItem based on the element Name property
-I was trying to call the Unsafe.Expand() method on this element
-I always got the same result --> NotSupportedException
Here are the infos what I can see in ACC Explorer tool:
![issue](https://user-images.githubusercontent.com/43213786/49325919-85719a80-f54a-11e8-9112-3f6cd8b2e08a.PNG)

Please see it and help me to resolve that issue.
Thanks is advance!

Georgie

**Comment by DavidWDev** [comment]
Hello,

maybe you're the wrong level?!
Can you please check that you have the right object found by the name. This you can do with the 'ElementFinder'.
The ElementFinder is a development support tool which shows you what the DW.CodedUI is see. What you can see there is what you can have access.
http://my-libraries.com/index.php/2-uncategorised/27-elementfinder-downloads
It helps you developing the target application.

I furthermore assume you do the BasicTreeViewItem by the UI.FindChild<BasicTreeViewItem>, right?
What type is your Tree Item?

Keep in mind that all methods in the 'Unsafe' are not meant to be used to productive test code, its only if we, when we need quick access somewhere but don't want to give away our mouse.
The normal right way would be to click it with the Mouse.

So, get the item and click on the expander on the left (Depending if its a LeftToRight application):

var element = UI.FindChild(By.Name("Peter"), From.LastWindow);
MouseEx.Click(element, At.Left(5));

Greeting
David

**Comment by Georgie89** [comment]
Hello again,

Thanks for your fast reply. You have right, I do not want to use unsafe
methods but sometimes could be very useful to use expand instead of
clicking. The click event will not check if the control is already expanded
and it can happen that a click method will collapse the treeviewitem
instead of expanding it.
Anyway, I am going to check the tool to ensure the level.
Until now I used a tool named ACC Explorer, and worked well with your
framework. I used the generic method of GetChild and my tree item is an
editable text, a WinEdit as I think. How should I define my treeviewitem
element? Until now i used like this:
public BasicTreeViewItem MyTreeViewItem =>
MyView.GetChild<BasicTreeViewItem>(By.Name(myName));
And MyView is the tree view container.
I am going to try the solutions you mentioned. In "worst" case I can use
mouse click as you have written.

Thanks again!
Georgie


2018. dec. 1., Szo 11:43 dátummal David W <notifications@github.com> ezt
írta:

**Comment by DavidWDev** [comment]
Hi,

the way you create the BasicTreeViewItem is right :-)
Maybe you try to expand the edit text box instead of the treeview item container... ?!

You can check for element.SupportedPatterns if there the ExpandCollapsePattern is available, only if so the Unsafe.Expand can be used.
http://libs.my-libraries.com/DW.CodedUI/v2.8.4/Documentation/html/P_DW_CodedUI_BasicElements_BasicElement_SupportedPatterns.htm

The mouse click of course will not check if the TreeViewItem is expanded, for that reason the BasicTreeViewItem has the Property IsExpanded.
See http://libs.my-libraries.com/DW.CodedUI/v2.8.4/Documentation/html/P_DW_CodedUI_BasicElements_BasicTreeViewItem_IsExpanded.htm
but before doing such it will be good to check if the catched item is the real tree item container or don't.

Greeting
David

**Comment by Georgie89** [comment]
Hello,

Your tool can see only this when I search for the tree view item:
[image: img.PNG]
I think the implementation of the control in our application could also be
wrong. That is why the ExpandCollapse pattern is not supported and I cannot
use neither Unsafe.Expand() method nor item.IsExpanded property.
Anyway, with MouseEx.Click() I could solve the issue. And as you wrote this
is the legal way to handle tree view items.

Best regards,
Georgie



David W <notifications@github.com> ezt írta (időpont: 2018. dec. 1., Szo,
18:54):

**Comment by DavidWDev** [comment]
Hi,

do you have a way to see if the item is expanded already?
An Idea I would have it to check the boundaries, I assume when children are visible the overall height of the parent item should be more.
If so you could write an own extension to the BasicTreeViewItem for checking if its expanded or not and if you have to click it.

**Comment by Georgie89** [comment]
Hi,

I could solve the problem with MouseEx.Click(), that was the easiest way to
do it.
I am quite sure that we have some weird control implementation in our app,
because our grid control does the same issue. I cannot use the
BasicDataCell GetItem()
method because of the same exception.

Greetings,
Georgie

David W <notifications@github.com> ezt írta (időpont: 2018. dec. 3., H,
9:31):

**Comment by DavidWDev** [comment]
Hi,

thanks for the response.
My library I tested with WPF and with Windows Forms with the most common libraries.
When it works bad, I'm sorry, but as you said, it can be some different implementation.

So, I took the freedom to close this issue here. If I can help with anything you're free to open a new issue or write me an e-Mail first :-)

Best wishes,
David
